# Nom du microcontroleur cible
# (exemple: 'at90s8515')
MCU=atmega324pa

# Nom de votre projet
# (utilisez un seul mot, exemple: 'monprojet')
PROJECTNAME=main

# Fichiers sources
# (Listez tous les fichiers a compiler, ex: 'tp1.c, tp2.cpp'):
# Utilisez le suffixe .cpp pour les fichiers C++
PRJSRC= main.cpp

# Inclusions additionnels (ex: -I/path/to/mydir)
INC=-I ../lib

# Libraires a lier (ex: -lmylib)
LIBS=-L ../lib

-include ../Makefile_principal.txt

